development:
  yahoo:
    consumer_key: "dj0yJmk9dkJxT3RkS2ljTk5FJmQ9WVdrOWRUUjFWVEkzTXpRbWNHbzlNVGt5T1RBeE1ERTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD1mYQ--"
    consumer_secret: "2d3e43aee471b6b110ec1ec0a3dc0d55c5ce84f2"